# Generated by Django 4.0.5 on 2022-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=50)),
                ('profile_image', models.CharField(default=None, max_length=300)),
                ('date_of_birth', models.CharField(default=None, max_length=30)),
                ('age', models.PositiveIntegerField(default=None)),
                ('place_of_birth', models.CharField(default=None, max_length=30)),
                ('citizenship', models.CharField(default=None, max_length=30)),
                ('height', models.PositiveIntegerField(default=None)),
                ('position', models.CharField(default=None, max_length=30)),
                ('current_international', models.CharField(default=None, max_length=30)),
                ('caps', models.PositiveIntegerField(default=None)),
                ('goals', models.PositiveIntegerField(default=None)),
                ('club', models.CharField(default=None, max_length=50)),
                ('joined_club', models.CharField(default=None, max_length=30)),
                ('contract_expires', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
