# Generated by Django 4.0.5 on 2022-06-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=50)),
                ('age', models.PositiveIntegerField(default=None)),
                ('styles', models.ManyToManyField(related_name='footballers', to='styles.style')),
            ],
        ),
    ]
