# Generated by Django 4.0.5 on 2022-06-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='caps',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='contract_expires',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='current_international',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='height',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='joined_club',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='footballer',
            name='profile_image',
        ),
    ]
