# Generated by Django 4.0.5 on 2022-07-01 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        ('footballers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footballers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='footballer',
            name='styles',
            field=models.ManyToManyField(related_name='footballers', to='styles.style'),
        ),
    ]
