# Generated by Django 4.0.5 on 2022-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
        ('footballers', '0002_remove_footballer_caps_remove_footballer_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='styles',
            field=models.ManyToManyField(related_name='footballers', to='styles.style'),
        ),
    ]
