# Generated by Django 4.0.5 on 2022-06-15 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footballers', '0002_footballer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
