# Generated by Django 4.0.5 on 2022-06-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0002_footballer_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='profile_image',
        ),
    ]
