# Generated by Django 4.0.5 on 2022-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0004_footballer_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballer',
            name='profile_image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
