# Generated by Django 4.0.5 on 2022-06-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0009_remove_footballer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='profile_image',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
