# Generated by Django 4.0.5 on 2022-06-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0010_footballer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='caps',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='footballer',
            name='citizenship',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='club',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='footballer',
            name='contract_expires',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='current_international',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='date_of_birth',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='goals',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='footballer',
            name='height',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='footballer',
            name='joined_club',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='place_of_birth',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='footballer',
            name='position',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
