# Generated by Django 4.0.5 on 2022-06-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0011_footballer_caps_footballer_citizenship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballer',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='footballer',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
