# Generated by Django 4.0.5 on 2022-06-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0012_rename_full_name_footballer_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='continent',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
