# Generated by Django 4.0.5 on 2022-06-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0013_footballer_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballer',
            name='continent',
        ),
    ]
