# Generated by Django 4.0.5 on 2022-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0014_remove_footballer_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballer',
            name='continent',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
